name = "Devs Kitchen"
author = "DiamondDEV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b48abf7eb6f162d27a442f7add53f185d352a2ffe44ddede58052308f44dc78"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
