name = "Devs Kitchen"
author = "DiamondDEV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "310e0b3f2653de9cad081b3b3ead309af44264a9a227b33bf9caec73ec497af3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
